### ISSUE TITLE
Malicious Advertisements 

### ISSUE THREAD

**Issue by tanaybhardwaj24** [deepjyoti30/ytmdl-web-v2#13]
## I have no problems with the dev adding advertisements but when i opened ytmdl today i found an advertisement for the adware flow cannot believe the dev would do this

**Comment by deepjyoti30** [comment]
@tanaybhardwaj24 What adware are you talking about? You can check the source. The app just uses Googles adsense for ads.

No other ads are injected by me to the code. Perhaps you should report the ad to Google.

**Comment by deepjyoti30** [comment]
@tanaybhardwaj24 Are you talking about the following ad?

![screenshot-2021-04-26_12-55-44](https://user-images.githubusercontent.com/33604454/116044838-02a78800-a68f-11eb-8e83-ad47c40df61c.jpg)

If that's what you were aiming at, that ad was **NOT** added by me. It's Google who handles the ads that are shown in the app.

Moreover, I think the ads are shown based on peoples search history (as tracked by Google). I would suggest you to report the ad.

However, please don't point fingers. You can check the source code of the app (it's Open Source, duh!) and see that I **do not personally inject any ads**.

**Comment by tanaybhardwaj24** [comment]
A -- Thanks for responding I now understand its not your fault

B-- Yes i got the same ad

btw, love your projects i use the startpage extension and ytmdl!!

**Comment by deepjyoti30** [comment]
@tanaybhardwaj24 Really appreciate that you disabled your adblock. If you had been an user of the app for a while, you might know that I really did not want to go for ads, however the server costs are just not bearable and the donations were very less so I had to finally add ads.

I will close the issue now!
