### ISSUE TITLE
Entering youtube url does not do anything

### ISSUE THREAD

**Issue by aahnik** [deepjyoti30/ytmdl-web-v2#16]
I am running locally the latest docker image. 

I did

```shell
➜ docker run -d -p 8082:8082 ghcr.io/deepjyoti30/ytmdl-web:latest
```

```
➜ docker images
# muliple lines removed for brevity
ghcr.io/deepjyoti30/ytmdl-web   latest           ea075682d661   7 weeks ago   136MB
```

The search bar claims that we can enter YouTube URLs.

![image](https://user-images.githubusercontent.com/66209958/119816694-a2646a00-bf0a-11eb-8cf2-ea95fbe84412.png)

I pasted the youtube URL, but nothing seems to happen. Just a red lining appears.

Here is a gif showing my usage.

![ytmdl-web](https://user-images.githubusercontent.com/66209958/119816201-105c6180-bf0a-11eb-9761-eaf865d009b2.gif)

Below is the screenshot of devtools console.
![image](https://user-images.githubusercontent.com/66209958/119816389-47327780-bf0a-11eb-8109-fb481b022c69.png)

**Comment by deepjyoti30** [comment]
@aahnik It's just an issue with checking if the URL is an youtube one. Currently only URL's with `https://youtube.com/watch?v=<videoID>` are considered valid ones.

Also the red indicator on the search bar indicates that the URL is invalid. I think adding a more verbose message would be better!

**Comment by aahnik** [comment]
> It's just an issue with checking if the URL is a youtube one

I had thought that. 

Now, I checked that `youtube.com` styled URLs work perfectly fine.

But I want to **request a feature** that please allow `youtu.be/<video id>` styled URLs. That the default that youtube gives when you copy the URL.

I believe it has to do with the validator that you use to check if the URL is valid.

**Comment by deepjyoti30** [comment]
@aahnik Yes. I would have already added it but I never came across that link. I'll make the changes!

**Comment by deepjyoti30** [comment]
@aahnik This took a while but it's finally here. `youtu.be` URL's are now supported on ytmdl web. I will close this issue.
