### ISSUE TITLE
Build failed :(

### ISSUE THREAD

**Issue by iTzBlack007** [deepjyoti30/ytmdl-web-v2#2]
ERROR  Failed to compile with 2 errors                               2:43:34 pm

 error  in ./src/App.vue?vue&type=style&index=0&lang=scss&

TypeError: Object.entries(...).flatMap is not a function
    at Array.forEach (<anonymous>)
    at new Promise (<anonymous>)

 @ ./src/App.vue?vue&type=style&index=0&lang=scss& 1:0-480 1:0-480
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/scss/_tailwind.scss

TypeError: getProcessedPlugins is not a function
    at new Promise (<anonymous>)

 @ ./src/main.js 9:0-31
 @ multi ./src/main.js

 ERROR  Build failed with errors.

**Comment by deepjyoti30** [comment]
@iTzBlack007 Seems like an issue with `Tailwind`. Did you install the dependencies before building?

Also, take a look at this https://tailwindcss.com/docs/installation#post-css-7-compatibility-build . Might be some issue because of `PostCSS`. I never faced this issue with my builds though.

**Comment by iTzBlack007** [comment]
Ok nvm dockerized builds are perfect !
