### ISSUE TITLE
Says your song is ready but i can't download the song, using webapp btw

### ISSUE THREAD

**Issue by MDUnit64** [deepjyoti30/ytmdl-web-v2#24]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [x] Locally
- [x] On the official page

## Browser Details

- Name: <>
- Version: (If possible)

## Console Log

```console
Put log if you found one in the browsers console window
```

## Description

DESCRIBE THE ISSUE

## Expected Behaviour

SHARE WHAT THE EXPECTED BEHAVIOUR SHOULD BE

**Comment by deepjyoti30** [comment]
@MDUnit64 Thanks for reporting the issue. It is actually a known issue. This is similar to #12

**Comment by deepjyoti30** [comment]
@MDUnit64 Can you try the app now. I have switched the infrastructure a bit in the backend and it should be available way more now!

I'll close this now.

**Comment by vehosah** [comment]
> 
> 
> @MDUnit64 Thanks for reporting the issue. It is actually a known issue. This is similar to #12

i tried the web app,but the song doesn't download
