### ISSUE TITLE
Tauri webapp

### ISSUE THREAD

**Issue by fine2006** [deepjyoti30/ytmdl-web-v2#25]
# Feature Request

## Checklist

- [x] I've searched the bugtracker for similar feature requests including closed ones.
- [x] I will add the enhancement label to the issue.

## Description
Adding tauri framwork to the webapp, for an improved experience
Describe the feature
There are two ways:
1. Redirect the app to https://ytmdl.deepjyoti30.dev, and keep some backup assets bundled to show the internet error message
2. Bundle the complete app locally

Leaning to 1st method, as the 2nd one is giving small hiccups.
## Expected Behaviour

SHARE WHAT THE EXPECTED BEHAVIOUR SHOULD BE

**Comment by deepjyoti30** [comment]
@fine2006 I think the second app would be a better option for a desktop app? Everything working locally would be convenient for users. Let me know if I can help you in any way!

**Comment by fine2006** [comment]
Opened up #26 :D

**Comment by fine2006** [comment]
Closing the issue as the related PR has been closed :)
