### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [deepjyoti30/ytmdl-web-v2#3]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by deepjyoti30** [comment]
@TechnologyClassroom Thanks for pointing that out. I just missed adding the License. I usually go for `MIT` for all my projects so I'm doing the same for this one as well!

Thanks again for raising the issue!

**Comment by deepjyoti30** [comment]
Fixed in 35fdafc5d1545cdb78a8656f6aa4a848c42bcb81
