### ISSUE TITLE
stuck your song is ready

### ISSUE THREAD

**Issue by vehosah** [deepjyoti30/ytmdl-web-v2#31]
# Bug report
im using the webapp,it says your song is ready but never downloads
## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run
it run fine until your song is ready
- [x] Locally
- [x] On the official page

## Browser Details
firefox 90.1
- Name: <firefox>
- Version:90.1

## Console Log

```console
Put log if you found one in the browsers console window
```

## Description

that the song doesn't download

## Expected Behaviour
i excepted the song to be downloaded?

**Comment by deepjyoti30** [comment]
@vehosah Thanks for reporting the issue. It's fixed now!

It was an API outage. Turns out all the nodes for the API were running out of space.
