### ISSUE TITLE
Stuck At "Your song is ready!"

### ISSUE THREAD

**Issue by ArmagdoGaming** [deepjyoti30/ytmdl-web-v2#32]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: <Firefox>
- Version: Latest one.

## Console Log

```console
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-152084173-5”. download:11:1
Service worker has been registered. registerServiceWorker.js:14:14
Service worker event waitUntil() was passed a promise that rejected with 'TypeError: NetworkError when attempting to fetch resource.'. workbox-precaching.prod.js:1:3354
New content is downloading. registerServiceWorker.js:20:14
onmozfullscreenchange is deprecated. minerkill.js:22:7
onmozfullscreenerror is deprecated. minerkill.js:22:7
Error: Promised response from onMessage listener went out of scope vendors.chunk.js:1:337063
TypeError: this.downloadDetails.size is undefined
    getSize DownloadResult.vue:92
    VueJS 3
    i DownloadResult.vue:1
    VueJS 21
vue.runtime.esm.js:1888:12

```

## Description

After selecting/adding the metadata, the app takes me to the download page, but only shows the message "Your song is ready!", without showing the download button, or downloading anything.

## Expected Behaviour

A button should appear that would allow me to download the song, but it doesn't appear.

![image](https://user-images.githubusercontent.com/52860974/146429500-a3ee93a3-c716-489f-b403-948ed90b4889.png)

**Comment by deepjyoti30** [comment]
@ArmagdoGaming Could you try again now?

I have added a fix and tested the web version, it's working fine. The issue was with the core `ytmdl` package which depends on `youtube-dl` for the downloads. `youtube-dl` recently released a new version that fixes a lot of issues (including the one that was breaking ytmdl).

Please consider checking the web app now, it should be fixed!

**Comment by ArmagdoGaming** [comment]
@deepjyoti30 I have tried it again, and got the same error, just more stuff written in the console.
`Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=UA-152084173-5”. download:11:1
Service worker has been registered. registerServiceWorker.js:14:14
Service worker event waitUntil() was passed a promise that rejected with 'TypeError: NetworkError when attempting to fetch resource.'. workbox-precaching.prod.js:1:3354
New content is downloading. registerServiceWorker.js:20:14
TypeError: this.downloadDetails.size is undefined
    getSize DownloadResult.vue:92
    get chunk-vendors.4889a9ef.js:7
    evaluate chunk-vendors.4889a9ef.js:7
    pr chunk-vendors.4889a9ef.js:7
    i DownloadResult.vue:1
    _render chunk-vendors.4889a9ef.js:7
    r chunk-vendors.4889a9ef.js:7
    get chunk-vendors.4889a9ef.js:7
    nr chunk-vendors.4889a9ef.js:7
    zn chunk-vendors.4889a9ef.js:7
    $mount chunk-vendors.4889a9ef.js:7
    init chunk-vendors.4889a9ef.js:7
    h chunk-vendors.4889a9ef.js:7
    d chunk-vendors.4889a9ef.js:7
    w chunk-vendors.4889a9ef.js:7
    d chunk-vendors.4889a9ef.js:7
    O chunk-vendors.4889a9ef.js:7
    j chunk-vendors.4889a9ef.js:7
    To chunk-vendors.4889a9ef.js:7
    _update chunk-vendors.4889a9ef.js:7
    r chunk-vendors.4889a9ef.js:7
    get chunk-vendors.4889a9ef.js:7
    run chunk-vendors.4889a9ef.js:7
    Jn chunk-vendors.4889a9ef.js:7
    he chunk-vendors.4889a9ef.js:7
    ue chunk-vendors.4889a9ef.js:7
    promise callback*ie chunk-vendors.4889a9ef.js:7
    he chunk-vendors.4889a9ef.js:7
    tr chunk-vendors.4889a9ef.js:7
    update chunk-vendors.4889a9ef.js:7
    notify chunk-vendors.4889a9ef.js:7
    set chunk-vendors.4889a9ef.js:7
    set chunk-vendors.4889a9ef.js:7
    t Download.vue:100
    l runtime.js:63
    n runtime.js:293
    S runtime.js:118
    Babel 8
    e Download.vue:83
    mounted Download.vue:135
    ne chunk-vendors.4889a9ef.js:7
    Fn chunk-vendors.4889a9ef.js:7
    insert chunk-vendors.4889a9ef.js:7
    ne chunk-vendors.4889a9ef.js:7
    n chunk-vendors.4889a9ef.js:7
    $ chunk-vendors.4889a9ef.js:7
    To chunk-vendors.4889a9ef.js:7
    _update chunk-vendors.4889a9ef.js:7
    r chunk-vendors.4889a9ef.js:7
    get chunk-vendors.4889a9ef.js:7
    run chunk-vendors.4889a9ef.js:7
    Jn chunk-vendors.4889a9ef.js:7
    he chunk-vendors.4889a9ef.js:7
    ue chunk-vendors.4889a9ef.js:7
    promise callback*ie chunk-vendors.4889a9ef.js:7
    he chunk-vendors.4889a9ef.js:7
    tr chunk-vendors.4889a9ef.js:7
    update chunk-vendors.4889a9ef.js:7
    notify chunk-vendors.4889a9ef.js:7
    set chunk-vendors.4889a9ef.js:7
    init chunk-vendors.4889a9ef.js:18
    init chunk-vendors.4889a9ef.js:18
chunk-vendors.4889a9ef.js:7:12041
    oe chunk-vendors.4889a9ef.js:7
    re chunk-vendors.4889a9ef.js:7
    ee chunk-vendors.4889a9ef.js:7
    _render chunk-vendors.4889a9ef.js:7
    r chunk-vendors.4889a9ef.js:7
    get chunk-vendors.4889a9ef.js:7
    nr chunk-vendors.4889a9ef.js:7
    zn chunk-vendors.4889a9ef.js:7
    $mount chunk-vendors.4889a9ef.js:7
    init chunk-vendors.4889a9ef.js:7
    h chunk-vendors.4889a9ef.js:7
    d chunk-vendors.4889a9ef.js:7
    w chunk-vendors.4889a9ef.js:7
    d chunk-vendors.4889a9ef.js:7
    O chunk-vendors.4889a9ef.js:7
    j chunk-vendors.4889a9ef.js:7
    To chunk-vendors.4889a9ef.js:7
    _update chunk-vendors.4889a9ef.js:7
    r chunk-vendors.4889a9ef.js:7
    get chunk-vendors.4889a9ef.js:7
    run chunk-vendors.4889a9ef.js:7
    Jn chunk-vendors.4889a9ef.js:7
    he chunk-vendors.4889a9ef.js:7
    ue chunk-vendors.4889a9ef.js:7
    (Async: promise callback)
    ie chunk-vendors.4889a9ef.js:7
    he chunk-vendors.4889a9ef.js:7
    tr chunk-vendors.4889a9ef.js:7
    update chunk-vendors.4889a9ef.js:7
    notify chunk-vendors.4889a9ef.js:7
    set chunk-vendors.4889a9ef.js:7
    set chunk-vendors.4889a9ef.js:7
    t Download.vue:100
    l runtime.js:63
    n runtime.js:293
    S runtime.js:118
    Babel 8
    e Download.vue:83
    mounted Download.vue:135
    ne chunk-vendors.4889a9ef.js:7
    Fn chunk-vendors.4889a9ef.js:7
    insert chunk-vendors.4889a9ef.js:7
    ne chunk-vendors.4889a9ef.js:7
    n chunk-vendors.4889a9ef.js:7
    $ chunk-vendors.4889a9ef.js:7
    To chunk-vendors.4889a9ef.js:7
    _update chunk-vendors.4889a9ef.js:7
    r chunk-vendors.4889a9ef.js:7
    get chunk-vendors.4889a9ef.js:7
    run chunk-vendors.4889a9ef.js:7
    Jn chunk-vendors.4889a9ef.js:7
    he chunk-vendors.4889a9ef.js:7
    ue chunk-vendors.4889a9ef.js:7
    (Async: promise callback)
    ie chunk-vendors.4889a9ef.js:7
    he chunk-vendors.4889a9ef.js:7
    tr chunk-vendors.4889a9ef.js:7
    update chunk-vendors.4889a9ef.js:7
    notify chunk-vendors.4889a9ef.js:7
    set chunk-vendors.4889a9ef.js:7
    init chunk-vendors.4889a9ef.js:18
    init chunk-vendors.4889a9ef.js:18
Error: Promised response from onMessage listener went out of scope vendors.chunk.js:1:337063
`

**Comment by ArmagdoGaming** [comment]
Works now, so I am closing this.

**Comment by HundredYearsSolitude** [comment]
![image](https://user-images.githubusercontent.com/97599346/159173736-08f55adc-179e-4585-a7e7-ca625f203cd7.png)
i just faced this problem on the website.
browser: ungoogled-chromium (flatpak build)

got these in console 
---
www.googletagmanager.com/gtag/js?id=UA-152084173-5:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
registerServiceWorker.js:14 Service worker has been registered.
registerServiceWorker.js:20 New content is downloading.
registerServiceWorker.js:17 Content has been cached for offline use.
registerServiceWorker.js:8 App is being served from cache by a service worker.
For more details, visit https://goo.gl/AFskqB
/metadata?videoId=Orym2NH3uUI&query=ya%20hayyo%20ya%20qayyum:1 Mixed Content: The page at 'https://www.ytmdl.deepjyoti30.dev/metadata?videoId=Orym2NH3uUI&query=ya%20hayyo%20ya%20qayyum' was loaded over HTTPS, but requested an insecure element 'http://a10.gaanacdn.com/images/albums/44/2557644/crop_480x480_2557644.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.ch40m1um.qjz9zk/2019/10/no-more-mixed-messages-about-https.html
/metadata?videoId=Orym2NH3uUI&query=ya%20hayyo%20ya%20qayyum:1 Mixed Content: The page at 'https://www.ytmdl.deepjyoti30.dev/metadata?videoId=Orym2NH3uUI&query=ya%20hayyo%20ya%20qayyum' was loaded over HTTPS, but requested an insecure element 'http://a10.gaanacdn.com/images/albums/44/2557644/crop_480x480_2557644.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.ch40m1um.qjz9zk/2019/10/no-more-mixed-messages-about-https.html
apis.deepjyoti30.dev/v2/ytmdl/download:1          Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'readable')
    at a.getSize (DownloadResult.vue:92:40)
    at nr.get (vue.runtime.esm.js:4479:25)
    at nr.evaluate (vue.runtime.esm.js:4584:21)
    at a.getSize (vue.runtime.esm.js:4836:17)
    at a.i (DownloadResult.vue?06dd:1:1047)
    at a.t._render (vue.runtime.esm.js:3548:22)
    at a.r (vue.runtime.esm.js:4066:21)
    at nr.get (vue.runtime.esm.js:4479:25)
    at new nr (vue.runtime.esm.js:4468:12)
    at zn (vue.runtime.esm.js:4073:3)
oe @ vue.runtime.esm.js:1888
/metadata?videoId=Orym2NH3uUI&query=ya%20hayyo%20ya%20qayyum:1 Mixed Content: The page at 'https://www.ytmdl.deepjyoti30.dev/metadata?videoId=Orym2NH3uUI&query=ya%20hayyo%20ya%20qayyum' was loaded over HTTPS, but requested an insecure element 'http://a10.gaanacdn.com/images/albums/44/2557644/crop_480x480_2557644.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.ch40m1um.qjz9zk/2019/10/no-more-mixed-messages-about-https.html
apis.deepjyoti30.dev/v2/ytmdl/download:1          Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'readable')
    at a.getSize (DownloadResult.vue:92:40)
    at nr.get (vue.runtime.esm.js:4479:25)
    at nr.evaluate (vue.runtime.esm.js:4584:21)
    at a.getSize (vue.runtime.esm.js:4836:17)
    at a.i (DownloadResult.vue?06dd:1:1047)
    at a.t._render (vue.runtime.esm.js:3548:22)
    at a.r (vue.runtime.esm.js:4066:21)
    at nr.get (vue.runtime.esm.js:4479:25)
    at new nr (vue.runtime.esm.js:4468:12)
    at zn (vue.runtime.esm.js:4073:3)
oe @ vue.runtime.esm.js:1888

**Comment by deepjyoti30** [comment]
@HundredYearsSolitude Are you still facing this?

It's a common error that happens with some songs (possibly because ytmdl is unable to dw those songs due to some reason)
