### ISSUE TITLE
"Getting the song ready for you" loading for too long

### ISSUE THREAD

**Issue by KelvinMvungi** [deepjyoti30/ytmdl-web-v2#55]
# Bug report

## How was Ytmdl Web run
[-] [On the official page

## Browser Details

- Name: < Brave>
- Version: (1.42.97)

## Console Log
DevTools failed to load source map: Could not load content for https://ytmdl.deepjyoti30.dev/js/chunk-1ec7a5f6.7343065e.js.map: Load canceled due to load timeout

## Description
The page when I paste the link from youtube is loading for too long currently I'm on it but it has loaded for like 20 mins and still going.

## Expected Behaviour
The page to load faster and get a download button to choose my format and quality then download it

We like to paste URLs from youtube because we love to get the actual audio quality which the singer/musician uploaded hence third party apps and searching from here I think it reduces the quality a bit.
Other wise GREAT WORK!

**Comment by deepjyoti30** [comment]
@KelvinMvungi Do you still get the error? As of now, I don't see any error downloading any song. Would like to know if you're still able to reproduce this so that I can look into it.
