### ISSUE TITLE
Add more tags

### ISSUE THREAD

**Issue by thaynos** [deepjyoti30/ytmdl-web-v2#56]
Adding more tags would make finding this repo way ezier, this is a very minor thing but i think adding more wud give more exposure, for example when i searched “music download” this did not show up at all. Or maybe is it that you dont want to be found?

**Comment by deepjyoti30** [comment]
@thaynos Thanks for the suggestion. I would like to get this repo more exposure. I'll add some more tags (that I can think of). Do share the tags that you think we can add to this repo.

**Comment by thaynos** [comment]
music download
online music 
online download
spotify download
free music
free music download
