### ISSUE TITLE
Can't find songs when using another device, server running docker-compose

### ISSUE THREAD

**Issue by petercockroach** [deepjyoti30/ytmdl-web-v2#6]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [x] Locally
- [ ] On the official page

## Browser Details

- Name: Brave / Safari
- Version: n/a, doesn't seem browser specific

## Console Log

```console
Put log if you found one in the browsers console window
```
Access to fetch at 'https://ytmdlapi.herokuapp.com/search?q=foobar' from origin 'http://192.168.1.100:8082' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

## Description

I'm running ytmdl-web on my server. When I try and search for a song on any other client device, I don't get any results. It's just a continuous search. I get the error above in console (not smart enough to understand what CORS policy is all about). 

## Expected Behaviour

Search results are delivered. This works fine if I use localhost:8082 on my server.

**Comment by deepjyoti30** [comment]
@petercockroach Thanks for reporting the issue. This is just a backend issue. So the API does not allow requests from all domains, however I had whitelisted the `localhost:8082` domain but I did not whitelist the `192.168.*.*` domain.

Thus, this means the webapp doesn't work on devices that try to run it through the local network. I will attempt to add a fix for this!

**Comment by deepjyoti30** [comment]
@petercockroach Can you try now. It should be fixed.

**Comment by petercockroach** [comment]
I can confirm. Thank you!
