### ISSUE TITLE
Queries can't have spaces.

### ISSUE THREAD

**Issue by Eviepayne** [deepjyoti30/ytmdl-web-v2#7]
I haven't peeked at the source but I suspect the query isn't sanitized. Should parse spaces to _

![image](https://user-images.githubusercontent.com/59463208/110047719-60b59000-7d1c-11eb-9e37-643500b78491.png)

![image](https://user-images.githubusercontent.com/59463208/110047773-79be4100-7d1c-11eb-920c-816563a9f05e.png)

**Comment by deepjyoti30** [comment]
@Eviepayne The spaces are parsed to `%20` automatically by VueJS. When the query is passed to the server, the API is able to parse the spaces as well.

I am not sure how you were able to get the first image above. Usually when you will enter a space in the query, it will be parsed to `%20`
