### ISSUE TITLE
Weird bug about downloading MP3s

### ISSUE THREAD

**Issue by BalintXHD** [deepjyoti30/ytmdl-web-v2#77]
# Bug report

## Checklist

- [x] I will add the bug label to this issue.
- [x] I have searched for similar bugs in the issues.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: Firefox

## Description

I can't download mp3s anymore, I had to switch to m4a to download this: https://www.youtube.com/watch?v=DDsx3j3S4qc
It gets stuck at "Your Song is Ready" part and doesn't display the actual song.

## Expected Behaviour

Mp3 downloads working as well as M4A downloads.

**Comment by BalintXHD** [comment]
Very strange... I had to switch to OPUS to download this: https://youtu.be/W4C-NEWrnSQ

**Comment by BalintXHD** [comment]
And I cannot at all download this, no matter what I do: https://youtu.be/hV-8xBnyVlY

**Comment by deepjyoti30** [comment]
> Very strange... I had to switch to OPUS to download this: https://youtu.be/W4C-NEWrnSQ

Just confirmed that downloading this is working fine. Can you try it again? I have just added a fix for the app.

> And I cannot at all download this, no matter what I do: https://youtu.be/hV-8xBnyVlY
This one as well worked perfectly fine for me. I downloaded it in mp3.

I would ask you to retry now as there is a new version of the app released and report back here if you still see the issue. I will close this as I have confirmed that this is working now.
