### ISSUE TITLE
Website app is down

### ISSUE THREAD

**Issue by BalintXHD** [deepjyoti30/ytmdl-web-v2#84]
# Bug report
## How was Ytmdl Web run
- [x] On the official page

## Description
The website is down, and according to this website, it's been a week. 
![kép](https://github.com/deepjyoti30/ytmdl-web-v2/assets/36235183/7dac73af-5ba4-4769-9b5e-5b60800d1ca4)
[link](https://www.isitdownrightnow.com/ytmdl.deepjyoti30.dev.html)

## Expected Behaviour
Website not down. :D

**Comment by deepjyoti30** [comment]
@BalintXHD Thanks for reporting the issue. It should be resolved now. The domain was recently transferred from Google domains to Squarespace (as they shut down). Yesterday, I moved it to Cloudflare and some settings over there caused all websites attached to that domain to go down.

I have verified that it is up and running now.

**Comment by deepjyoti30** [comment]
Closing. Please re-open if you see it not being resolved.
